/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/ethereum/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a nonce for Ethereum wallet authentication */
        get: operations["ethereum_nonce"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/ethereum/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Ethereum wallet signature and authenticate */
        post: operations["ethereum_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset code */
        post: operations["forgot_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email/phone and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and invalidate session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available authentication methods for this site */
        get: operations["auth_methods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["refresh_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with code */
        post: operations["reset_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/send-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send OTP code to email or phone (passwordless login) */
        post: operations["send_otp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/solana/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a nonce for Solana wallet authentication */
        get: operations["solana_nonce"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/solana/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Solana wallet signature and authenticate */
        post: operations["solana_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email or phone with code */
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify OTP code and sign in (creates account if doesn't exist) */
        post: operations["verify_otp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start OAuth flow (redirects to provider) */
        get: operations["oauth_start"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth callback (exchanges code for tokens)
         *     Returns an HTML page that posts credentials to the parent window
         */
        get: operations["oauth_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get comments for a page */
        get: operations["get_comments"];
        put?: never;
        /** Create a new comment */
        post: operations["create_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a comment */
        put: operations["update_comment"];
        post?: never;
        /** Delete a comment (marks as deleted, preserves replies) */
        delete: operations["delete_comment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a comment for moderation */
        post: operations["report_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vote on a comment */
        post: operations["vote_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/approve/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a pending comment (moderator+) */
        post: operations["approve_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/ban/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ban a user from commenting (moderator+)
         *     Optionally delete all their comments on this site
         */
        post: operations["ban_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pending comments for moderation (moderator+) */
        get: operations["get_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/reject/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a pending comment (moderator+) */
        post: operations["reject_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user reports (moderator+) */
        get: operations["get_reports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/shadowban/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shadowban a user (comments appear to them but invisible to others) */
        post: operations["shadowban_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/unban/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unban a user (moderator+) */
        post: operations["unban_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user notifications */
        get: operations["get_notifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark all notifications as read */
        post: operations["mark_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/my_votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's votes for a page */
        get: operations["get_my_votes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{page_id}/posting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get page posting status (admin+) */
        get: operations["get_page_posting_status"];
        /** Enable or disable posting on a specific page (admin+) */
        put: operations["set_page_posting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get site admins (owner only - requires secret API key) */
        get: operations["get_admins"];
        put?: never;
        /** Add a site admin (owner only - requires secret API key) */
        post: operations["add_admin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}/admins/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a site admin (owner only - requires secret API key) */
        delete: operations["remove_admin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all comments on the site (moderator+)
         * @description Returns a paginated list of all comments on the site, sorted by creation time (newest first).
         *     Useful for site-wide moderation views.
         */
        get: operations["get_site_comments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}/moderators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get site moderators (admin+) */
        get: operations["get_moderators"];
        put?: never;
        /** Add a site moderator (admin+) */
        post: operations["add_moderator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}/moderators/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a site moderator (admin+) */
        delete: operations["remove_moderator"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}/posting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get site-wide posting status (admin+) */
        get: operations["get_posting_status"];
        /** Enable or disable site-wide posting (admin+) */
        put: operations["set_site_posting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/turnstile/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve the Turnstile challenge page (opened in popup)
         * @description This page loads the Cloudflare Turnstile widget and sends the token
         *     back to the parent window via postMessage when complete.
         */
        get: operations["challenge_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/turnstile/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Turnstile configuration for this site */
        get: operations["get_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/turnstile/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a Turnstile token server-side
         * @description This endpoint verifies the token with Cloudflare's API.
         *     Used by the server when processing comment submissions.
         */
        post: operations["verify_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/check-username": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check if a username is available */
        post: operations["check_username"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["get_me"];
        /** Update current user profile */
        put: operations["update_me"];
        post?: never;
        /** Delete current user account (GDPR) */
        delete: operations["delete_account"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/blocked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of users blocked by current user */
        get: operations["get_blocked_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's comments on this site */
        get: operations["get_my_comments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user's public profile */
        get: operations["get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block a user (hide their comments from you) */
        post: operations["block_user"];
        /** Unblock a user */
        delete: operations["unblock_user"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user's public comments on this site */
        get: operations["get_user_comments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddUserRequest: {
            /**
             * Format: uuid
             * @description User ID to add to role
             */
            user_id: string;
        };
        AuthMethod: {
            /** @description Method identifier (email, phone, google, github, ethereum, solana) */
            id: string;
            /** @description Human-readable name */
            name: string;
            /** @description Method type: "oauth", "otp", "web3" */
            type: string;
        };
        AuthMethodsResponse: {
            /** @description Available authentication methods for this site */
            methods: components["schemas"]["AuthMethod"][];
        };
        AuthResponse: {
            /** @description JWT refresh token (longer lived) */
            refresh_token: string;
            /** @description JWT access token */
            token: string;
            /** @description User details */
            user: components["schemas"]["UserResponse"];
        };
        BanUserRequest: {
            /** @description If true, delete all of user's comments on this site */
            delete_comments?: boolean;
        };
        BanUserResponse: {
            /**
             * Format: int64
             * @description Number of comments deleted (if delete_comments was true)
             */
            comments_deleted: number;
        };
        BlockedUsersResponse: {
            /** @description List of blocked users */
            users: components["schemas"]["UserPublic"][];
        };
        CheckUsernameRequest: {
            /** @description Username to check */
            username: string;
        };
        CheckUsernameResponse: {
            /** @description Whether the username is available */
            available: boolean;
            /** @description Validation error if username format is invalid */
            error?: string | null;
        };
        Comment: {
            /** Format: uuid */
            author_id: string;
            content: string;
            content_html: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            depth: number;
            /** Format: int64 */
            downvotes: number;
            edited: boolean;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            page_id: string;
            page_url: string;
            /** Format: uuid */
            parent_id?: string | null;
            /** Format: int64 */
            reply_count: number;
            /** Format: uuid */
            site_id: string;
            status: components["schemas"]["CommentStatus"];
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            upvotes: number;
        };
        /** @description A comment item with page context */
        CommentItem: {
            /** @description The comment */
            comment: components["schemas"]["TreeComment"];
            /**
             * Format: uuid
             * @description Page ID where the comment exists
             */
            page_id: string;
        };
        /** @enum {string} */
        CommentStatus: "pending" | "approved" | "rejected" | "deleted";
        CommentWithAuthor: components["schemas"]["Comment"] & {
            author: components["schemas"]["UserPublic"];
            user_vote?: null | components["schemas"]["VoteDirection"];
        };
        /** @description Request to create a new comment */
        CreateCommentRequest: {
            /** @description Display name for anonymous comments (required if not authenticated) */
            author_name?: string | null;
            /** @description Comment content (markdown) */
            content: string;
            /** @description URL of the page */
            page_url: string;
            /**
             * @description Path to parent comment (array of UUIDs from root to parent)
             *     Empty array or omitted for root-level comments
             */
            parent_path?: string[];
        };
        /** @description Response when a comment is created */
        CreateCommentResponse: {
            /** @description The created comment in compact tree format */
            comment: components["schemas"]["TreeComment"];
        };
        DeleteRequest: {
            /** @description Page URL where the comment exists */
            page_url: string;
            /** @description Path to the comment (array of UUIDs from root to target) */
            path: string[];
        };
        DeletedAccountStats: {
            /** Format: int64 */
            comments_deleted: number;
            /** Format: int64 */
            votes_deleted: number;
        };
        ForgotPasswordRequest: {
            /** @description Email address */
            email?: string | null;
            /** @description Phone number */
            phone?: string | null;
        };
        /** @description Response for GET /comments - uses compact tree format */
        GetCommentsResponse: {
            /**
             * Format: uuid
             * @description Page ID for WebSocket subscription
             */
            page_id: string;
            /**
             * Format: int64
             * @description Pageview count (if enabled)
             */
            pageviews?: number | null;
            /**
             * Format: int64
             * @description Total comment count
             */
            total: number;
            /** @description Comments in compact tree format (single-letter keys) */
            tree: components["schemas"]["PageTree"];
        };
        GetVotesResponse: {
            /** @description Map of comment ID to vote direction ("up" or "down") */
            votes: {
                [key: string]: string;
            };
        };
        LoginRequest: {
            /** @description Email address */
            email?: string | null;
            /** @description Password */
            password: string;
            /** @description Phone number */
            phone?: string | null;
        };
        MeResponse: {
            /** @description Avatar URL */
            avatar_url?: string | null;
            /** @description Email address (if set) */
            email?: string | null;
            /** @description Whether email is verified */
            email_verified: boolean;
            /**
             * Format: uuid
             * @description User ID
             */
            id: string;
            /**
             * Format: int64
             * @description User karma from votes
             */
            karma: number;
            /** @description Username */
            name: string;
            /** @description Phone number (if set) */
            phone?: string | null;
            /** @description Whether phone is verified */
            phone_verified: boolean;
            /** @description Social media links */
            social_links: components["schemas"]["SocialLinks"];
            /**
             * Format: int64
             * @description Number of unread notifications
             */
            unread_notifications: number;
            /** @description Whether the user has explicitly chosen their username */
            username_set: boolean;
        };
        ModerateCommentRequest: {
            /**
             * Format: uuid
             * @description Page ID where the comment is located
             */
            page_id: string;
            /** @description Path to the comment (array of UUIDs from root to target) */
            path: string[];
        };
        NonceResponse: {
            /** @description When the nonce expires */
            expiration_time: string;
            /** @description When the nonce was issued */
            issued_at: string;
            /** @description The message to sign */
            message: string;
            /** @description Nonce for this authentication request */
            nonce: string;
        };
        Notification: {
            /** Format: uuid */
            comment_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            from_user_id: string;
            /** Format: uuid */
            id: string;
            notification_type: components["schemas"]["NotificationType"];
            read: boolean;
        };
        /** @enum {string} */
        NotificationType: "reply" | "mention" | "upvote" | "mod_action";
        NotificationWithDetails: components["schemas"]["Notification"] & {
            from_user?: null | components["schemas"]["UserPublic"];
        };
        NotificationsResponse: {
            /** @description List of notifications */
            notifications: components["schemas"]["NotificationWithDetails"][];
            /**
             * Format: int64
             * @description Number of unread notifications
             */
            unread_count: number;
        };
        /** @description Page tree - all comments for a page in one JSON blob */
        PageTree: {
            /** @description comments (array of root comments) */
            c?: components["schemas"]["TreeComment"][];
            /**
             * Format: int64
             * @description updated_at (unix timestamp)
             */
            u: number;
        };
        PostingStatusResponse: {
            /** @description Whether posting is disabled */
            disabled: boolean;
        };
        QueueItem: {
            /** @description The pending comment */
            comment: components["schemas"]["TreeComment"];
            /**
             * Format: uuid
             * @description Page ID where the comment is located
             */
            page_id: string;
        };
        QueueResponse: {
            /** @description Pending comments with their page context */
            items: components["schemas"]["QueueItem"][];
            /** @description Total count */
            total: number;
        };
        RefreshRequest: {
            /** @description Refresh token from login/register */
            refresh_token: string;
        };
        RegisterRequest: {
            /** @description Email address (required if no phone) */
            email?: string | null;
            /** @description Username (must be unique) */
            name: string;
            /** @description Password */
            password: string;
            /** @description Phone number (required if no email) */
            phone?: string | null;
        };
        Report: {
            /** Format: uuid */
            comment_id: string;
            /** Format: date-time */
            created_at: string;
            details?: string | null;
            reason: components["schemas"]["ReportReason"];
            /** Format: uuid */
            reporter_id: string;
        };
        ReportItem: {
            comment?: null | components["schemas"]["TreeComment"];
            /**
             * Format: uuid
             * @description Comment ID that was reported
             */
            comment_id: string;
            /**
             * Format: uuid
             * @description Page ID where the reported comment is located
             */
            page_id: string;
            reporter?: null | components["schemas"]["UserPublic"];
        };
        /** @enum {string} */
        ReportReason: "spam" | "harassment" | "hate_speech" | "misinformation" | "other";
        ReportRequest: {
            /** @description Additional details */
            details?: string | null;
            /** @description Page URL where the comment exists */
            page_url: string;
            /** @description Path to the comment being reported */
            path: string[];
            /** @description Reason for the report */
            reason: components["schemas"]["ReportReason"];
        };
        ReportsResponse: {
            /** @description List of reports with comment info */
            items: components["schemas"]["ReportItem"][];
            /** @description Total count */
            total: number;
        };
        ResetPasswordRequest: {
            /** @description Reset code from email/SMS */
            code: string;
            /** @description Email address */
            email?: string | null;
            /** @description New password */
            new_password: string;
            /** @description Phone number */
            phone?: string | null;
        };
        RoleListResponse: {
            /** @description List of users with this role */
            users: components["schemas"]["UserPublic"][];
        };
        SendOtpRequest: {
            /** @description Email address (required if no phone) */
            email?: string | null;
            /** @description Phone number (required if no email) */
            phone?: string | null;
        };
        SetPostingRequest: {
            /** @description Set to true to disable posting, false to enable */
            disabled: boolean;
        };
        SiteCommentItem: {
            /** @description The comment data */
            comment: components["schemas"]["TreeComment"];
            /**
             * Format: uuid
             * @description Page ID where the comment was posted
             */
            page_id: string;
        };
        SiteCommentsResponse: {
            /** @description List of comments */
            comments: components["schemas"]["SiteCommentItem"][];
            /** @description Whether there are more comments available */
            has_more: boolean;
        };
        /** @description Social media links for a user's profile */
        SocialLinks: {
            discord?: string | null;
            facebook?: string | null;
            github?: string | null;
            instagram?: string | null;
            snapchat?: string | null;
            telegram?: string | null;
            tiktok?: string | null;
            twitter?: string | null;
            whatsapp?: string | null;
        };
        /** @enum {string} */
        SortOrder: "new" | "top" | "hot";
        /** @description Compact comment stored in page tree (single-letter keys) */
        TreeComment: {
            /**
             * Format: uuid
             * @description author_id
             */
            a: string;
            /**
             * Format: int64
             * @description downvotes count
             */
            d: number;
            /** @description html content (rendered) */
            h: string;
            /**
             * Format: uuid
             * @description id - comment UUID
             */
            i: string;
            /**
             * Format: int64
             * @description author karma
             */
            k: number;
            /**
             * Format: int64
             * @description modified_at (unix timestamp)
             */
            m: number;
            /** @description author name */
            n: string;
            /** @description author avatar (picture) */
            p?: string | null;
            /**
             * Format: uuid
             * @description parent_id - only used for WebSocket messages to indicate reply threading
             *     Not used in GET /comments (uses nested replies instead)
             */
            q?: string | null;
            /** @description replies (nested array of child comments) */
            r?: components["schemas"]["TreeComment"][];
            s?: null | components["schemas"]["CommentStatus"];
            /** @description text content (markdown) */
            t: string;
            /**
             * Format: int64
             * @description upvotes count
             */
            u: number;
            /**
             * Format: int64
             * @description created_at (unix timestamp)
             */
            x: number;
        };
        TurnstileConfigResponse: {
            /** @description Whether Turnstile is enabled for this site */
            enabled: boolean;
            /** @description When Turnstile is required */
            enforce_on: string;
            /** @description Whether the server has Turnstile configured (has secret key) */
            server_configured: boolean;
        };
        UpdateCommentRequest: {
            /** @description New comment content (markdown) */
            content: string;
            /** @description Page URL where the comment exists */
            page_url: string;
            /** @description Path to the comment (array of UUIDs from root to target) */
            path: string[];
        };
        UpdateMeRequest: {
            /** @description New avatar URL */
            avatar_url?: string | null;
            /** @description New username */
            name?: string | null;
            social_links?: null | components["schemas"]["SocialLinks"];
        };
        UserCommentsResponse: {
            /** @description List of comments */
            comments: components["schemas"]["CommentItem"][];
            /** @description Whether there are more comments available */
            has_more: boolean;
        };
        UserPublic: {
            avatar_url?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            karma: number;
            name: string;
            social_links?: null | components["schemas"]["SocialLinks"];
            /** Format: int64 */
            total_comments: number;
        };
        UserResponse: {
            avatar_url?: string | null;
            email?: string | null;
            email_verified: boolean;
            /** Format: uuid */
            id: string;
            name: string;
            phone?: string | null;
            phone_verified: boolean;
            /** @description Social media links */
            social_links: components["schemas"]["SocialLinks"];
            /**
             * @description Whether the user has explicitly chosen their username.
             *     If false, the user should be prompted to set their username.
             */
            username_set: boolean;
        };
        VerifyOtpRequest: {
            /** @description OTP code */
            code: string;
            /** @description Email address (required if no phone) */
            email?: string | null;
            /** @description Username (required for new accounts) */
            name?: string | null;
            /** @description Phone number (required if no email) */
            phone?: string | null;
        };
        VerifyRequest: {
            /** @description The token from Turnstile widget */
            token: string;
        };
        VerifyResponse: {
            /** @description Error codes if verification failed */
            error_codes?: string[];
            /** @description Whether the verification was successful */
            success: boolean;
        };
        /** @enum {string} */
        VoteDirection: "up" | "down";
        VoteRequest: {
            /** @description Vote direction (up or down) */
            direction: components["schemas"]["VoteDirection"];
            /** @description Page URL where the comment exists */
            page_url: string;
            /** @description Path to the comment (array of UUIDs from root to target) */
            path: string[];
        };
        VoteResponse: {
            /** Format: int64 */
            downvotes: number;
            /** Format: int64 */
            upvotes: number;
            user_vote?: null | components["schemas"]["VoteDirection"];
        };
        Web3VerifyRequest: {
            /** @description Wallet address */
            address: string;
            /** @description Signed message (the message field from NonceResponse) */
            message: string;
            /** @description Signature from wallet (hex for Ethereum, base58 for Solana) */
            signature: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ethereum_nonce: {
        parameters: {
            query: {
                /** @description Wallet address (0x... for Ethereum, base58 for Solana) */
                address: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nonce generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NonceResponse"];
                };
            };
            /** @description Invalid address format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ethereum_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Web3VerifyRequest"];
            };
        };
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid signature or expired nonce */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Signature verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgot_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Reset code sent (if account exists) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Account banned */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_methods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available auth methods */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMethodsResponse"];
                };
            };
        };
    };
    refresh_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email/phone/username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reset_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password reset successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    send_otp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendOtpRequest"];
            };
        };
        responses: {
            /** @description OTP sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    solana_nonce: {
        parameters: {
            query: {
                /** @description Wallet address (0x... for Ethereum, base58 for Solana) */
                address: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nonce generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NonceResponse"];
                };
            };
            /** @description Invalid address format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    solana_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Web3VerifyRequest"];
            };
        };
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid signature or expired nonce */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Signature verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Verification successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_otp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid or expired code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauth_start: {
        parameters: {
            query: {
                /** @description API key (required since OAuth is initiated via navigation, not fetch) */
                project_id: string;
            };
            header?: never;
            path: {
                /** @description OAuth provider (google, github) */
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to OAuth provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid API key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Provider not configured */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauth_callback: {
        parameters: {
            query: {
                /** @description OAuth authorization code */
                code: string;
                /** @description State parameter (site_id) */
                state?: string | null;
            };
            header?: never;
            path: {
                /** @description OAuth provider */
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth successful - returns HTML that posts to parent window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid OAuth response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Provider not supported */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_comments: {
        parameters: {
            query: {
                /** @description URL of the page to get comments for */
                page_url: string;
                /** @description Sort order (new, top, hot) */
                sort?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCommentsResponse"];
                };
            };
            /** @description Not modified (ETag match) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_comment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description Comment created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCommentResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is blocked or Turnstile verification failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Parent comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentRequest"];
            };
        };
        responses: {
            /** @description Comment updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeComment"];
                };
            };
            /** @description Not your comment */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteRequest"];
            };
        };
        responses: {
            /** @description Comment deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    report_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Report submitted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    vote_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteRequest"];
            };
        };
        responses: {
            /** @description Vote recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteResponse"];
                };
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateCommentRequest"];
            };
        };
        responses: {
            /** @description Comment approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a moderator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ban_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID to ban */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BanUserRequest"];
            };
        };
        responses: {
            /** @description User banned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BanUserResponse"];
                };
            };
            /** @description Cannot ban yourself */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot ban user with equal or higher role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_queue: {
        parameters: {
            query?: {
                /** @description Pagination offset */
                offset?: number;
                /** @description Max items to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moderation queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
            /** @description Not a moderator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reject_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateCommentRequest"];
            };
        };
        responses: {
            /** @description Comment rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a moderator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_reports: {
        parameters: {
            query?: {
                /** @description Pagination offset */
                offset?: number;
                /** @description Max items to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of reports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportsResponse"];
                };
            };
            /** @description Not a moderator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shadowban_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID to shadowban */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User shadowbanned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot shadowban yourself */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot shadowban user with equal or higher role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unban_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID to unban */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User unbanned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_notifications: {
        parameters: {
            query?: {
                /** @description Pagination offset */
                offset?: number;
                /** @description Max items to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mark_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications marked as read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_my_votes: {
        parameters: {
            query: {
                /** @description URL of the page to get votes for */
                page_url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User's votes for the page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetVotesResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_page_posting_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Page ID */
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page posting status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostingStatusResponse"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_page_posting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Page ID */
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPostingRequest"];
            };
        };
        responses: {
            /** @description Page posting status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostingStatusResponse"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_admins: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of admins */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleListResponse"];
                };
            };
            /** @description Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_admin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddUserRequest"];
            };
        };
        responses: {
            /** @description Admin added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_admin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                id: string;
                /** @description User ID to remove */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_site_comments: {
        parameters: {
            query?: {
                /** @description Number of comments to skip (default: 0) */
                offset?: number | null;
                /** @description Maximum number of comments to return (default: 50, max: 100) */
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Site ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of site comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteCommentsResponse"];
                };
            };
            /** @description Not a moderator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_moderators: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of moderators */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleListResponse"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_moderator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddUserRequest"];
            };
        };
        responses: {
            /** @description Moderator added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is already an admin */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_moderator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                id: string;
                /** @description User ID to remove */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moderator removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_posting_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Posting status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostingStatusResponse"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_site_posting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Site ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPostingRequest"];
            };
        };
        responses: {
            /** @description Posting status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostingStatusResponse"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    challenge_page: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML page with Turnstile widget */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Turnstile not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Turnstile configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnstileConfigResponse"];
                };
            };
        };
    };
    verify_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
            /** @description Turnstile not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    check_username: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckUsernameRequest"];
            };
        };
        responses: {
            /** @description Username availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckUsernameResponse"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedAccountStats"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_blocked_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of blocked users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedUsersResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_my_comments: {
        parameters: {
            query?: {
                /** @description Pagination offset */
                offset?: number;
                /** @description Max items to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User's comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCommentsResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    block_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID to block */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User blocked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot block yourself */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unblock_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID to unblock */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User unblocked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user_comments: {
        parameters: {
            query?: {
                /** @description Pagination offset */
                offset?: number;
                /** @description Max items to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description User ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User's comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCommentsResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
